#ifndef SCISTEPVIEWER_GLOBAL_H
#define SCISTEPVIEWER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SCISTEPVIEWER_LIBRARY)
#  define SCISTEPVIEWERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define SCISTEPVIEWERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SCISTEPVIEWER_GLOBAL_H
